
###
POST http://localhost:3000/items
Content-Type: application/json

{
     "title": "Equipo Aucas",
    "price": 1500,
    "image": "Aucas.jpg"
}

###
POST http://localhost:3000/create-payment-intent
Content-Type: application/json

[
    {
        "id": "5f87ebadbf386d24f40c286b",
        "qty": 2
    }
]

###
POST http://localhost:3000/order
Content-Type: application/json

{
    "email": "test@test.com",
    "items":[
        {
            "id": "5f87ebadbf386d24f40c286b",
            "qty": 2
        }
    ]
}